[package]
name = "lazrs"
version = "0.3.1"
authors = ["tmontaigu <thomas.montaigu@laposte.net>"]
edition = "2018"
license = "MIT"
description = "Python bindings for laz-rs"
readme = "README.md"

[lib]
name = "lazrs"
crate-type = ["cdylib"]

[dependencies.laz]
git = "https://github.com/tmontaigu/laz-rs"
rev = "fd7901ddfd083189795c4617c3450ecc028d6f15"
features = ["parallel"]

[dependencies.pyo3]
version = "0.12.4"
features = ["extension-module"]

[package.metadata.maturin]
classifier = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Programming Language :: Python",
    "Programming Language :: Rust",
]
