[package]
name = "lazrs"
version = "0.2.0"
authors = ["tmontaigu <thomas.montaigu@laposte.net>"]
edition = "2018"
license = "MIT"
description = "Python bindings for laz-rs"
readme = "README.md"

[lib]
name = "lazrs"
crate-type = ["cdylib"]

[dependencies]
numpy = "0.7.0"

[dependencies.laz]
version = "^0.4.0"
features = ["parallel"]

[dependencies.pyo3]
version = "0.8.5"
features = ["extension-module"]

[package.metadata.maturin]
classifier = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Programming Language :: Python",
    "Programming Language :: Rust",
]