[package]
name = "lazrs"
version = "0.2.3"
authors = ["tmontaigu <thomas.montaigu@laposte.net>"]
edition = "2018"
license = "MIT"
description = "Python bindings for laz-rs"
readme = "README.md"

[lib]
name = "lazrs"
crate-type = ["cdylib"]

[dependencies.laz]
version = "0.5.1"
features = ["parallel"]

[dependencies.pyo3]
version = "0.12.4"
features = ["extension-module"]

[package.metadata.maturin]
classifier = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Programming Language :: Python",
    "Programming Language :: Rust",
]
